startup/connect/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'connect'

urlpatterns = [
   path('login/', auth_views.LoginView.as_view(template_name="login.html"),name='login'),
   path('signup/', views.SignUp.as_view(), name="signup"),
   path('logout/',auth_views.LogoutView.as_view(), name="logout" ),
 ]

startup/groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name="all"),
    path('new/', views.CreateGroup.as_view(), name="create"),
    path(r'^posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name="single"),
    path(r'^join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name="join"),
    path(r'^leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name="leave"),
]

startup/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns=[
    path('',views.PostList.as_view(),name="postlist" ),
    path('createpost/',views.CreatePost.as_view(), name="create"),
    path('deletepost/', views.DeletePost.as_view(), name="delete"),
    path('userposts/', views.UserPosts.as_view(), name="user"),
]

startup/startup/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('connect/', include('connect.urls')),
    path('posts/',include('posts.urls')),
    path('groups/', include('groups.urls')),
    path('', views.HomePage.as_view(), name='home'),
     path('about/', views.AboutView.as_view(), name="About"),
]

startup/templates/about.html
{% extends "base.html" %}
{% block body_block %}

<div class="jumbotron col-3">
    <h1>About Connect media website!</h1>
    <h2>Welcome to our website, hope you rnjoy our services </h2>
    <h3>it targets people who want to connect with their loved ones, friends ,relatives and co-workers <br>
        and coneferences   
</h3>
</div>
{% endblock %}
{% block bottom %}
{% endblock %}

startup/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"></head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm bg-light justify-content-center">
      <div class="container">
        
        <ul class=" nav nav-pills " id="nav">
          {% if user.is_authenticated %}
             
              <li class="nav-item"><a class="nav-link" href="#"><i class="fas fa-user-circle"></i></a></li>
              <li class="nav-item-active"><a class="nav-link" href="{% url 'groups:all' %}"><i class="fas fa-user-friends"></i></a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'groups:create' %}" class="btn btn-success">Create Group</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'posts:delete' %}" class="btn btn-success">My post</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'posts:create' %}" class="btn btn-success">Post</a></li>
              <li class="nav-item"><a class="nav-link" href="#"><i class="fas fa-cog"></i></a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'connect:logout' %}" class="btn btn-success">Logout</a></li>
          {% else %}
              <li class="navbar-item"><a class="nav-link" href="{% url 'connect:signup' %}" class="btn btn-success">Signup</a></li>
              <li class="navbar-item"><a class="nav-link" href="{% url 'connect:login' %}" class="btn btn-success"><i>Login</i></a></li>
          {% endif %}
      </ul>

      </div>

    </nav>
    
      {% block body_block %}
      {% endblock %}

    </div>
    <nav class=" navbar navbar-expand-md bg-dark fixed-bottom  ">
      <div class="container">
        <div class="">
          <ul class=" nav nav-pills " >
            <li class="nav-item"><a class="nav-link" href="#"><i class="fab fa-facebook-square"></i></a></li>
            <li class="nav-item"><a class="nav-link" href="#"><i class="fab fa-twitter"></i></a></li>
            <li class="nav-item"><a class="nav-link" href="#"><i class="fab fa-instagram"></i></a></li>
            <li class="nav-item"><a class="nav-link" href="#"><i class="fas fa-copyright">connectInc</i></a></li>
            
          </ul>
  
        </div>
      </div>
  
      
    </nav>
    {% block bottom %}
    {% endblock %}
  </body>
</html>

startup/templates/home.html
{% extends "base.html" %}
{% block body_block %}
<div class="col-md-8" id="posts">
    {% include "posts/post_list.html" %}
</div>
{% endblock %}
{% block bottom %}
{% endblock %}