startup/groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name="all"),
    path('new/', views.CreateGroup.as_view(), name="create"),
    path(r'^posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name="single"),
    path(r'^join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name="join"),
    path(r'^leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name="leave"),
]

startup/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns=[
    path('',views.PostList.as_view(),name="postlist" ),
    path('createpost/',views.CreatePost.as_view(), name="create"),
    path('deletepost/', views.DeletePost.as_view(), name="delete"),
    path('userposts/', views.UserPosts.as_view(), name="user"),
]

startup/startup/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('connect/', include('connect.urls')),
    path('posts/',include('posts.urls')),
    path('groups/', include('groups.urls')),
    path('', views.HomePage.as_view(), name='home'),
     path('about/', views.AboutView.as_view(), name="About"),
]

startup/posts/models.py
from django.db import models

from django.conf import settings
from django.urls import reverse
from groups.models import Group
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE )
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.name,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user","group"]

startup/posts/forms.py
from django import forms
from . import models

class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

startup/posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy, reverse
from django.http import Http404
from django.views import generic
from . import forms
from . import models
from braces.views import SelectRelatedMixin
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

class PostList( SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ("user","message")


class UserPosts(generic.list.ListView):
    form_class = forms.PostForm
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_redirect_url(self,*args,**kwargs):
        return reverse("posts:postlist",kwargs={"user": self.kwargs.get("user.username")})



    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context

class CreatePost(LoginRequiredMixin, generic.CreateView,SelectRelatedMixin):
    form_class = forms.PostForm
    model = models.Post
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, generic.DeleteView,SelectRelatedMixin):
    form_class = forms.PostForm
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

startup/posts/templates/posts/_post.html
<div class="post media">
	<h3>{{ post.message_html|safe }}</h3>
	<div class="media-body">
		<strong>{{ post.user.username }}</strong>
		<h5 class="media-heading">
			<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">{{ post.user.username }}</a></span>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
			{% endif %}
		</h5>

		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">
                    <i class="fas fa-trash"></i>
				</a>
			{% endif %}
		</div>
	</div>
</div>

startup/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block body_block %}
<div class="posts-page">
	<div class="container">
		<div class="col-md-3">
			{% block prepost%}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post%}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

startup/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-small">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-primary">Cancel</a>
</form>

{% endblock %}

startup/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap3 %}

{% block post_content %}
<h4>Create New Post</h4>
<form method="POST" action="{% url 'posts:create' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-success">
</form>
{% endblock %}

startup/posts/templates/posts/post_list.html
{% extends "posts/post_list_base.html" %}
{% load humanize %}

{% block pre_post_content %}
<div class="col-md-4" id="prepost">
	{% if request.user.is_authenticated %}
	<div class="card card-image-overlay">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_groups as user_groups %}#}
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>
			



		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

startup/posts/templates/posts/post_list_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"></head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        
  </head>
  <body>

      <div class="posts-page">
          <div class="container">
              <div class="col-md-3">
                  {% block prepost%}{% endblock %}
                  {% block post_content %}{% endblock %}
                  {% block post_post%}{% endblock %}
              </div>
          </div>
      </div>
    
  </body>

startup/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in postlist %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}